int init_patchfinder64(uint64_t base/*, const char *filename*/);
void term_patchfinder64(void);
_Bool patchfinder64_is_initialised(void);
uint64_t find_allproc(void);
uint64_t find_add_x0_x0_0x40_ret(void);
uint64_t find_copyout(void);
uint64_t find_bzero(void);
uint64_t find_bcopy(void);
uint64_t find_rootvnode(void);
uint64_t find_trustcache(void);
uint64_t find_amficache(void);
uint64_t find_zone_map_ref(void);
